Repository marrink-lab/polyply_1.0, pull requests merged in 2023-09, with the labels that each got.

#276 Add PTMA AA FF to polyply library [10.1021/acs.macromol.3c00141]
  LIBRARY.md
  polyply/data/oplsaaLigParGen/CH3.ff
  polyply/data/oplsaaLigParGen/PTMA.oplsaa.LigParGen.ff
  polyply/data/oplsaaLigParGen/citations.bib
  polyply/data/oplsaaLigParGen/links_PTMA.ff
  polyply/tests/test_data/library_tests/oplsaaLigParGen/PTMA/polyply/PTMA.itp
  polyply/tests/test_data/library_tests/oplsaaLigParGen/PTMA/polyply/command
  polyply/tests/test_lib_files.py
Labels: parameter submission, hacktoberfest-accepted, wait_for_publication

#313 [1] Dna exten/itp
  bin/polyply
  polyply/data/martini2/DNA_M2.ff
  polyply/src/apply_links.py
  polyply/src/gen_dna.py
  polyply/src/gen_itp.py
  polyply/src/meta_molecule.py
  polyply/src/simple_seq_parsers.py
  polyply/tests/test_data/library_tests/parmbsc1/dsDNA/polyply/DNA.itp
  polyply/tests/test_data/library_tests/parmbsc1/dsDNA/polyply/command
  polyply/tests/test_data/library_tests/parmbsc1/dsDNA/ref.json
  polyply/tests/test_data/simple_seq_files/test_ig_warning.ig
  polyply/tests/test_gen_dna.py
  polyply/tests/test_gen_params.py
  polyply/tests/test_lib_files.py
  polyply/tests/test_simple_seq_parsers.py
Labels: DNA_extension

#321 Box from coords
  polyply/src/gen_coords.py
  polyply/src/topology.py
  polyply/tests/test_data/topology_test/meta.gro
  polyply/tests/test_data/topology_test/test.gro
  polyply/tests/test_data/topology_test/test.pdb
  polyply/tests/test_gen_coords_logic.py
  polyply/tests/test_topology.py
  setup.cfg
Labels: enhancement, wait_for_vermouth
